spring:
  application:
    name: store-invoice-api
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:contrasena_segura}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
    validate-on-migrate: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost} # Cambiado a la IP de tus logs para desarrollo, o vuelve a poner localhost si usas túneles
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    ssl:
      enabled: false
  cloud:
    function:
      definition: recibirPedido;processFinalState
    stream:
      bindings:
        processFinalState-in-0:
          destination: ${ESTADO_FINAL_TRANSPORTE_QUEUE:estadopedido} # <--- CORREGIDO: Ahora el fallback coincide con tu cola de RabbitMQ
          group: estadopedido
          consumer:
            max-attempts: 3
        recibirPedido-in-0:
          destination: ${PEDIDOS_INVENTARIO_QUEUE:pedidos.inventario}
          group: ${PEDIDOS_INVENTARIO_QUEUE:pedidos.inventario}
          consumer:
            max-attempts: 3
      rabbit:
        bindings:
          processFinalState-in-0:
            consumer:
              queueNameGroupOnly: true   # <--- CORREGIDO: Movido al bloque correcto de Rabbit
              declareExchange: false     # <--- CORREGIDO: Movido al bloque correcto de Rabbit
              bindQueue: false           # <--- CORREGIDO: Movido al bloque correcto de Rabbit
              auto-bind-dlq: true
              republish-to-dlq: true
              dlq-name: ${ESTADO_FINAL_DLQ:estado.final.transporte.dlq}
          recibirPedido-in-0:
            consumer:
              queueNameGroupOnly: true
              declareExchange: false
              bindQueue: false
              auto-bind-dlq: true
              dlq-name: ${PEDIDOS_INVENTARIO_DLQ:pedidos.inventario.dlq}
              republish-to-dlq: true

logging:
  level:
    com.storeinvoice.storeinvoiceapi: DEBUG
    com.storeinvoice.storeinvoiceapi.application.service.liquidacion.cliente.ProcesarPedidoInventarioUseCase: DEBUG
    com.storeinvoice.storeinvoiceapi.infrastructure.adapter.outbound.external: DEBUG
