spring.application.name=store-invoice-api
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.password=mysecretpassword
spring.datasource.username=postgres

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

